### ISSUE TITLE
Support for position (request)

### ISSUE THREAD

**Issue by christophemarois** [pianosnake/uke-chord#1]
The `nut` parameter is a good indicator of whether we are in the first position or not, but it would be good to also have a position indicator, like [vexchord](https://github.com/tombatossals/vexchords) does, for example:

![image](https://cloud.githubusercontent.com/assets/811336/22750131/a34a4044-edfd-11e6-9dbf-6d0744e5c4ff.png)

Outstanding work, thank you very much!

**Comment by pianosnake** [comment]
Thanks for the compliment and good suggestion. I've implemented it in the latest version, see 0.5.1.
