### ISSUE TITLE
How to use it with webpack & Reactjs

### ISSUE THREAD

**Issue by guanw** [pianosnake/uke-chord#2]
Hi,
   I am trying to add the this uke-chord to my react project but can't figure out a way to render it. I use webpack to do the packing and attached is my webpack.config.js, but on the webpage it seems like <uke-chord> is being treated as a XML tag. Could you help me figure this out?

![uke](https://cloud.githubusercontent.com/assets/7311035/25463042/5eab3514-2ac1-11e7-93ab-8eb0af6cbcc0.jpg)

**Comment by pianosnake** [comment]
Hard to tell with just a config file. Do you have a link to project?
