### ISSUE TITLE
How to x a string?

### ISSUE THREAD

**Issue by selfpublish** [pianosnake/uke-chord#3]
Florin,

Loving `<uke-chord>`! Thank you for creating it! Have you ever considered adding way to x out a string that shouldn't be played? Example:

![](https://assets.codepen.io/769788/image_40.png)

Which would be triggered with something like: 

`<uke-chord frets="022x"></uke-chord>`

I created a codepen with your awesome JS if you want to check it out (or fork it) and hope you don't mind:

https://codepen.io/pubwriter/pen/abNNMbZ

Thanks,
Brian

**Comment by pianosnake** [comment]
Hi Brian, 
Good idea!  Done. 
![image](https://user-images.githubusercontent.com/1406711/90349921-b6cd1b00-dff8-11ea-9fd7-aac0c4a480d4.png)

**Comment by selfpublish** [comment]
You rock! Thanks so much. It's absolutely perfect now!
